#!/usr/bin/bash
year='2025'
startdate='April 5, '$year
enddate='April 6, '$year
new='moqp1x1ses.html'
old='old_moqp1x1ses.html'
#record start of process
date
cd /home/pi/Projects/status1x1
if [ -f "$new" ]; then
    rm $old
    mv $new $old
fi
#Fetch allocated calls from 1x1callsigns.org
./sestationreport.py --startdate "$startdate" --enddate "$enddate"
if [ -f "$new" ]; then
    diff $new $old
else
    echo "Fetch of updated call list failed to complete."
fi

#Use scp to copy file to w0ma.org
scp ./moqp1x1ses.html w0ma@w0ma.org:/home/w0ma/mo_qso_party/results/$year/reports/
#record end of process
date
